#!/bin/bash 

# Written by SB 2020
# This is to configure my bash settings

# Execute 'oc login' first

nodes=$(oc get nodes -o jsonpath='{.items[*].metadata.name}')
for node in ${nodes[@]}
do
    echo "==== Shut down $node ===="
    ssh core@$node sudo shutdown -h 1
done